_include: !include hackBase.yaml

epochs: 20
batch_size: 256
data_train_view_files: ['hack/trainConfigs/train_unsupervised.txt']   # relative path to the train view file lists
print_freq: 50
plot_freq: 5
debug: True

backbone_model: Cnn6

# To use a torchvision Net
# backbone_model: resnet18
# backbone_kwargs: [{ "zero_init_residual": True}]

data_plot_min_limits: {'loss': 0.0}
data_plot_max_limits: {'loss': 12000.0}

data_transforms_1: [
    ['LibrPitch', {'sr': 16000, 'pRange': 6}],
    ['MelSpectrogram' , {'n_fft': 1024, 'hop_length': 800, 'n_mels': 64}],
    ['ExpandDim', {'dim': 0}],
  ]
data_transforms_2: [
    ['LibrPitch', {'sr': 16000, 'pRange': 6}],
    ['MelSpectrogram' , {'n_fft': 1024, 'hop_length': 800, 'n_mels': 64}],
    ['ExpandDim', {'dim': 0}],
  ]

data_batch_transforms_1: [
    ['NormalizeInputBatch', {'chanCount': 64, 'transpose': [1, 2]}] 
  ]
data_batch_transforms_2: [
    ['NormalizeInputBatch', {'chanCount': 64, 'transpose': [1, 2]}] 
  ]
