_include: !include hackBase.yaml

epochs: 1000
music_classifier_epochs: 50
music_classifier_learning_rate: 0.001
batch_size: 1024
data_train_bin_path: ['hack/music-detection-data/sl_training_set_v1/', 'hack/music-detection-data/music-detection-unlabeled/', 'hack/music-detection-data/audioset/']  # relative path to the binary data files
data_train_view_files: ['hack/trainConfigs/supervised_train_v04.txt', 'hack/trainConfigs/music_notLabeled_16572_10secOnly.txt', 'hack/trainConfigs/audioset_470742_16000.txt']   # relative path to the train view file lists
data_val_bin_path: ['hack/music-detection-data/sl_training_set_v1/'] 
data_val_view_files: ['hack/trainConfigs/unsupervised_val_v04.txt']

print_freq: 50
plot_freq: 5
val_freq: 4
early_stop_patience: 20

# For short tests
# data_train_bin_path: ['hack/music-detection-data/sl_training_set_v1']  # relative path to the binary data files
# data_train_view_files: ['hack/trainConfigs/short_40.txt']   # relative path to the train view file lists
# data_suptrain_bin_path: ['hack/music-detection-data/sl_training_set_v1'] # supervised training
# data_suptrain_view_files: ['hack/trainConfigs/short_40.txt']    # supervised training
# data_supval_bin_path: ['hack/music-detection-data/sl_training_set_v1'] # supervised val (during train)
# data_supval_view_files: ['hack/trainConfigs/short_40.txt']    # supervised val (during train)
# data_supval_bin_path: ['hack/music-detection-data/sl_training_set_v1'] # supervised val (during train
# data_suptest_view_files: ['hack/trainConfigs/short_40.txt']    # supervised eval run
# data_suptest_bin_path: ['hack/music-detection-data/sl_training_set_v1'] # supervised eval run)


operations: ['train_unsupervised', 'train_supervised', 'eval_supervised']


# To use a torchvision Net
backbone_model: resnet18
backbone_kwargs: [{ "zero_init_residual": True}]

data_plot_min_limits: {'loss': 0.0}
data_plot_max_limits: {'loss': 12000.0}

data_transforms_1: [
    ['LibrPitch', {'sr': 16000, 'pRange': 6}],
    ['MelSpectrogram' , {'n_fft': 1024, 'hop_length': 800, 'n_mels': 64}],
    ['ExpandDim', {'dim': 0}],
  ]
data_transforms_2: [
    ['LibrPitch', {'sr': 16000, 'pRange': 6}],
    ['MelSpectrogram' , {'n_fft': 1024, 'hop_length': 800, 'n_mels': 64}],
    ['ExpandDim', {'dim': 0}],
  ]

sup_data_transforms: [ 
    ['MelSpectrogram' , {'n_fft': 1024, 'hop_length': 800, 'n_mels': 64}],
    ['ExpandDim', {'dim': 0}] 
  ]
